server:
  port: 8000

spring:
  session:
    store-type: redis
    timeout: 1800s
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: 192.168.10.130
    port: 6379
    timeout: 5000ms

